// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmwaotzgsnnlzrqjgpcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptd2FvdHpnc25ubHpycWpncGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzU1MTEsImV4cCI6MjA3MDMxMTUxMX0._S1XQ42U-IDH2Xu3t1rMM4HvDGrE4_x_PK_QyceIsbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});